require('./board-test.js');
require('./game-test.js');
require('./light-test.js');
require('./levels-test.js');
require('./score-test.js');
require('./messages-test.js');
require('./next-move-test.js');
require('./neighbor-coords-test.js');
require('./relative-coords-test.js');
